import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Activity, BarChart3, Bot, BriefcaseBusiness, CalendarClock, ChevronRight, CreditCard, FileText, LayoutDashboard, LogOut, Menu, MessageCircle, MessagesSquare, RefreshCw, Send, Settings, ShieldCheck, Smartphone, Users, Wallet, X, Zap} from 'lucide-react';
import {api,get,post,patch,del} from './api';
import './styles.css';

const NAV=[
 {group:'Principal',items:[['dashboard','Dashboard',LayoutDashboard],['accounts','Cuentas Telegram',Smartphone],['messages','Mensajes',MessageCircle],['messages-pro','Mensajes Pro',MessagesSquare],['forwarder','Reenviador',Send],['campaigns','Campañas',Zap]]},
 {group:'Gestión',items:[['content','Contenido',FileText],['scheduled','Posts programados',CalendarClock],['payments','Pagos',Wallet],['payment-detector','Detector de pagos',Wallet],['whatsapp','WhatsApp',MessageCircle],['reports','Informes',BarChart3],['team','Equipo',Users],['payroll','Nóminas',BriefcaseBusiness],['agencies','Agencias',BriefcaseBusiness],['guiones','Guiones',FileText],['sfs','SFS',Bot],['jaj','JAJ',Zap],['promo','Grupos promocionales',Users],['free-channels','Canales',Send]]},
 {group:'Sistema',items:[['security','Seguridad',ShieldCheck],['settings','Configuración',Settings],['system','Estado del sistema',Activity]]}
];
const labels=Object.fromEntries(NAV.flatMap(g=>g.items.map(x=>[x[0],x[1]])));

function App(){
 const [session,setSession]=useState({loading:true,me:null});
 const [page,setPage]=useState('dashboard');
 const [mobile,setMobile]=useState(false);
 const [refresh,setRefresh]=useState(0);
 useEffect(()=>{get('/api/auth/me').then(me=>setSession({loading:false,me})).catch(()=>setSession({loading:false,me:null}))},[]);
 if(session.loading)return <div className="login"><div className="login-card"><div className="logo">LUREQO <span>CRM</span></div><p className="muted">Comprobando sesión…</p></div></div>;
 if(!session.me?.worker && !session.me?.ownerName)return <Login onLogin={me=>setSession({loading:false,me})}/>;
 const me=session.me;
 return <div className="app"><div className={'overlay '+(mobile?'open':'')} onClick={()=>setMobile(false)} />
  <aside className={'sidebar '+(mobile?'open':'')}><div className="brand"><div className="logo">LUREQO <span>CRM</span></div><div className="muted" style={{fontSize:12,marginTop:5}}>Control center</div></div>
   {NAV.map(g=><div key={g.group}><div className="nav-section">{g.group}</div>{g.items.map(([id,name,Icon])=><button key={id} className={'nav-item '+(page===id?'active':'')} onClick={()=>{setPage(id);setMobile(false)}}><Icon size={17}/><span>{name}</span></button>)}</div>)}
   <div style={{marginTop:'auto',padding:12}}><button className="nav-item" onClick={async()=>{await post('/api/auth/logout',{});location.reload()}}><LogOut size={17}/>Cerrar sesión</button></div>
  </aside>
  <main className="main"><header className="topbar"><div style={{display:'flex',alignItems:'center',gap:12}}><button className="mobile-btn" onClick={()=>setMobile(true)}><Menu size={19}/></button><div><b>{labels[page]||'LUREQO CRM'}</b><div className="muted" style={{fontSize:11}}>Plataforma operativa</div></div></div><button className="btn secondary" onClick={()=>setRefresh(x=>x+1)}><RefreshCw size={15}/> Actualizar</button></header><div className="content"><Page page={page} refresh={refresh} me={me}/></div></main>
 </div>
}

function Login({onLogin}){const [identifier,setIdentifier]=useState(''),[password,setPassword]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');return <div className="login"><div className="login-card"><div className="logo">LUREQO <span>CRM</span></div><h1 style={{fontSize:27,margin:'28px 0 6px'}}>Bienvenido</h1><p className="muted">Accede al centro de operaciones.</p><form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{await post('/api/auth/unified-login',{identifier,password});onLogin(await get('/api/auth/me'))}catch(err){setError(err.message)}finally{setBusy(false)}}}><div className="field"><label>Usuario o email</label><input value={identifier} onChange={e=>setIdentifier(e.target.value)} autoComplete="username"/></div><div className="field"><label>Contraseña</label><input type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password"/></div>{error&&<div className="pill bad" style={{marginBottom:14}}>{error}</div>}<button className="btn" style={{width:'100%'}} disabled={busy}>{busy?'Entrando…':'Iniciar sesión'}</button></form></div></div>}

function Page({page,refresh}){switch(page){case'dashboard':return <Dashboard refresh={refresh}/>;case'accounts':return <Accounts refresh={refresh}/>;case'campaigns':return <Campaigns refresh={refresh}/>;case'forwarder':return <Forwarder refresh={refresh}/>;case'messages':return <Messages refresh={refresh}/>;case'messages-pro':return <MessagesPro/>;case'scheduled':return <Scheduled refresh={refresh}/>;case'reports':return <Reports/>;case'payments':return <SimpleModule title="Pagos" icon={Wallet} endpoints={['/api/incoming-payments','/api/payment-accounts']}/>;case'content':return <SimpleModule title="Contenido" icon={FileText} endpoints={['/api/accounts']}/>;case'payment-detector':return <SimpleModule title="Detector de pagos" icon={Wallet} endpoints={['/api/payment-detector/history']}/>;case'whatsapp':return <SimpleModule title="WhatsApp" icon={MessageCircle} endpoints={['/api/whatsapp']}/>;case'team':return <SimpleModule title="Equipo" icon={Users} endpoints={['/api/workers','/api/work-hours']}/>;case'agencies':return <SimpleModule title="Agencias" icon={BriefcaseBusiness} endpoints={['/api/agencies']}/>;case'payroll':return <SimpleModule title="Nóminas" icon={BriefcaseBusiness} endpoints={['/api/payroll','/api/model-payroll']}/>;case'guiones':return <SimpleModule title="Guiones" icon={FileText} endpoints={['/api/accounts']}/>;case'sfs':return <SimpleModule title="SFS" icon={Bot} endpoints={['/api/accounts']}/>;case'jaj':return <SimpleModule title="JAJ" icon={Zap} endpoints={['/api/jap/balance','/api/jap/eur-rate']}/>;case'promo':return <SimpleModule title="Grupos promocionales" icon={Users} endpoints={['/api/promo-groups']}/>;case'free-channels':return <SimpleModule title="Canales" icon={Send} endpoints={['/api/accounts']}/>;case'security':return <SimpleModule title="Seguridad" icon={ShieldCheck} endpoints={['/api/security']}/>;case'settings':return <SimpleModule title="Configuración" icon={Settings} endpoints={['/api/settings']}/>;default:return <Dashboard refresh={refresh}/>}}

function Dashboard(){const [d,setD]=useState(null),[err,setErr]=useState('');useEffect(()=>{get('/api/informes/dashboard-summary').then(setD).catch(e=>setErr(e.message))},[]);return <><h1 className="page-title">Dashboard</h1><p className="page-subtitle">Resumen operativo de tu CRM.</p>{err&&<div className="pill bad">{err}</div>}<div className="grid stats">{[['Ventas hoy',d?.salesToday?.length??0],['Ventas mes',d?.salesMonth?.length??0],['Envíos hoy',d?.sentToday??0],['Errores hoy',d?.errorsToday??0]].map(([l,v])=><div className="card" key={l}><div className="stat-label">{l}</div><div className="stat-value">{v}</div></div>)}</div><div className="grid two" style={{marginTop:16}}><div className="card"><h3>Estado de cuentas</h3><div className="list">{(d?.accounts||[]).slice(0,8).map(a=><div className="list-row" key={a.id}><span>{a.label}</span><span className={'pill '+(a.health==='OK'?'ok':'warn')}>{a.health||'—'}</span></div>)}</div>{!d&&<div className="empty">Cargando datos…</div>}</div><div className="card"><h3>Campañas</h3><div className="list">{Object.entries((d?.campaigns||[]).reduce((m,c)=>(m[c.status]=(m[c.status]||0)+1,m),{})).map(([k,v])=><div className="list-row" key={k}><span>{k}</span><b>{v}</b></div>)}</div></div></div></>}

function Accounts({refresh}){const [data,setData]=useState(null);useEffect(()=>{get('/api/accounts').then(setData)},[refresh]);return <><PageHeader title="Cuentas Telegram" subtitle="Gestiona las sesiones y el interruptor maestro del reenviador."/><div className="table-wrap"><table className="table"><thead><tr><th>Cuenta</th><th>Teléfono</th><th>Salud</th><th>Reenviador</th><th>Campañas</th><th>Origenes</th><th></th></tr></thead><tbody>{(data?.accounts||[]).map(a=><tr key={a.id}><td><b>{a.label}</b></td><td>{a.phoneNumber||'—'}</td><td><span className={'pill '+(a.health==='OK'?'ok':'warn')}>{a.health||'—'}</span></td><td><span className={'pill '+(a.reenviadorEnabled?'ok':'')}>{a.reenviadorEnabled?'Activo':'Pausado'}</span></td><td>{a._count?.campaigns??0}</td><td>{a._count?.sourceGroups??0}</td><td><AccountToggle a={a}/></td></tr>)}</tbody></table></div>{!data&&<div className="empty">Cargando cuentas…</div>}</>}
function AccountToggle({a}){const [busy,setBusy]=useState(false);return <button className="btn secondary" disabled={busy} onClick={async()=>{setBusy(true);await patch('/api/accounts/'+a.id,{reenviadorEnabled:!a.reenviadorEnabled});location.reload()}}>{a.reenviadorEnabled?'Pausar':'Activar'}</button>}

function Campaigns({refresh}){const [accounts,setAccounts]=useState([]),[selected,setSelected]=useState('');const [data,setData]=useState(null);useEffect(()=>{get('/api/accounts').then(x=>{setAccounts(x.accounts);if(x.accounts[0])setSelected(x.accounts[0].id)})},[]);useEffect(()=>{if(selected)get('/api/accounts/'+selected+'/campaigns').then(setData)},[selected,refresh]);return <><PageHeader title="Campañas" subtitle="Configuración real de campañas conectada a la API actual."/><div className="toolbar"><select value={selected} onChange={e=>setSelected(e.target.value)}>{accounts.map(a=><option key={a.id} value={a.id}>{a.label}</option>)}</select></div><div className="list">{(data?.campaigns||[]).map(c=><div className="card" key={c.id}><div style={{display:'flex',justifyContent:'space-between',gap:15,alignItems:'center'}}><div><b>{c.folderName}</b><div className="muted" style={{fontSize:12,marginTop:4}}>{c.scheduleMode} · {c.sendMode} · {c.destinationChats?.length||0} destinos</div></div><div style={{display:'flex',gap:8}}><span className={'pill '+(c.status==='ACTIVE'?'ok':'warn')}>{c.status}</span><button className="btn secondary" onClick={async()=>{await patch('/api/campaigns/'+c.id,{status:c.status==='ACTIVE'?'PAUSED':'ACTIVE'});setData(await get('/api/accounts/'+selected+'/campaigns'))}}>{c.status==='ACTIVE'?'Pausar':'Activar'}</button><button className="btn danger" onClick={async()=>{if(confirm('¿Eliminar campaña?')){await del('/api/campaigns/'+c.id);setData(await get('/api/accounts/'+selected+'/campaigns'))}}}>Eliminar</button></div></div></div>)}{data?.campaigns?.length===0&&<div className="empty">No hay campañas para esta cuenta.</div>}</div></>}

function Forwarder({refresh}){const [accounts,setAccounts]=useState([]),[selected,setSelected]=useState('');const [next,setNext]=useState(null);useEffect(()=>{get('/api/accounts').then(x=>{setAccounts(x.accounts);if(x.accounts[0])setSelected(x.accounts[0].id)})},[]);useEffect(()=>{if(selected)get('/api/accounts/'+selected+'/next-send').then(setNext)},[selected,refresh]);return <><PageHeader title="Reenviador" subtitle="Centro de control del motor de reenvío, sin cambiar su backend."/><div className="grid two"><div className="card"><h3>Cuenta</h3><select style={{width:'100%'}} value={selected} onChange={e=>setSelected(e.target.value)}>{accounts.map(a=><option key={a.id} value={a.id}>{a.label}</option>)}</select><p className="muted">El interruptor maestro se controla desde Cuentas Telegram.</p></div><div className="card"><h3>Próximo envío</h3>{next?.nextSend?<><div className="stat-value">{next.nextSend.timeOfDay}</div><div className="muted">{next.nextSend.folderName} · {next.nextSend.when} · {next.timezone}</div></>:<div className="empty">Sin horario fijo pendiente.</div>}</div></div><Campaigns refresh={refresh}/></>}

function Messages({refresh}){const [accounts,setAccounts]=useState([]),[account,setAccount]=useState(''),[dialogs,setDialogs]=useState([]),[chat,setChat]=useState(null),[msgs,setMsgs]=useState([]),[text,setText]=useState('');useEffect(()=>{get('/api/accounts').then(x=>{setAccounts(x.accounts);if(x.accounts[0])setAccount(x.accounts[0].id)})},[]);useEffect(()=>{if(account)get('/api/accounts/'+account+'/dialogs').then(x=>setDialogs(x.dialogs||[])).catch(()=>setDialogs([]))},[account,refresh]);useEffect(()=>{if(account&&chat)get('/api/accounts/'+account+'/dialogs/'+encodeURIComponent(chat.id)+'/messages').then(x=>setMsgs(x.messages||[])).catch(()=>setMsgs([]))},[account,chat,refresh]);const send=async()=>{if(!text.trim()||!chat)return;await post('/api/accounts/'+account+'/dialogs/'+encodeURIComponent(chat.id)+'/send',{text});setText('');setMsgs(await get('/api/accounts/'+account+'/dialogs/'+encodeURIComponent(chat.id)+'/messages').then(x=>x.messages||[]))};return <><PageHeader title="Mensajes" subtitle="Conversaciones Telegram con la API existente."/><div className="toolbar"><select value={account} onChange={e=>{setAccount(e.target.value);setChat(null)}}>{accounts.map(a=><option key={a.id} value={a.id}>{a.label}</option>)}</select></div><div className="split"><div className="card" style={{maxHeight:620,overflow:'auto'}}><h3>Conversaciones</h3><div className="list">{dialogs.map(d=><button key={d.id} className={'nav-item '+(chat?.id===d.id?'active':'')} onClick={()=>setChat(d)}>{d.title||d.name||d.id}</button>)}{!dialogs.length&&<div className="empty">No hay conversaciones disponibles.</div>}</div></div><div className="card chat"><div className="messages">{msgs.map((m,i)=><div key={m.id||i} className={'bubble '+(m.out?'mine':'')}>{m.text||m.message||'[media]'}</div>)}</div><div style={{display:'flex',gap:8,marginTop:12}}><textarea className="field textarea" value={text} onChange={e=>setText(e.target.value)} placeholder={chat?'Escribe un mensaje…':'Selecciona una conversación'} disabled={!chat}/><button className="btn" onClick={send} disabled={!chat||!text.trim()}>Enviar</button></div></div></div></>}

function MessagesPro(){return <SimpleModule title="Mensajes Pro" icon={MessagesSquare} endpoints={['/api/mensajes-pro/accounts']}/>}
function Scheduled({refresh}){const [accounts,setAccounts]=useState([]),[selected,setSelected]=useState(''),[posts,setPosts]=useState([]);useEffect(()=>{get('/api/accounts').then(x=>{setAccounts(x.accounts);if(x.accounts[0])setSelected(x.accounts[0].id)})},[]);useEffect(()=>{if(selected)get('/api/accounts/'+selected+'/scheduled-posts').then(x=>setPosts(x.posts||x.scheduledPosts||[]))},[selected,refresh]);return <><PageHeader title="Posts programados" subtitle="Agenda y consulta publicaciones desde la API existente."/><div className="toolbar"><select value={selected} onChange={e=>setSelected(e.target.value)}>{accounts.map(a=><option key={a.id} value={a.id}>{a.label}</option>)}</select></div><div className="list">{posts.map(p=><div className="list-row" key={p.id}><div><b>{p.title||p.text?.slice(0,70)||'Post'}</b><div className="muted">{p.scheduledAt||p.runAt||'—'}</div></div><span className="pill">{p.status||'PROGRAMADO'}</span></div>)}{!posts.length&&<div className="empty">No hay publicaciones programadas.</div>}</div></>}
function Reports(){const [d,setD]=useState(null);useEffect(()=>{get('/api/informes/dashboard-summary').then(setD)},[]);return <><PageHeader title="Informes" subtitle="Indicadores operativos conectados a la base de datos."/><div className="grid stats">{[['Ventas hoy',d?.salesToday?.length??'—'],['Ventas mes',d?.salesMonth?.length??'—'],['Envíos',d?.sentToday??'—'],['Errores',d?.errorsToday??'—']].map(([l,v])=><div className="card" key={l}><div className="stat-label">{l}</div><div className="stat-value">{v}</div></div>)}</div></>}
function SimpleModule({title,icon:Icon,endpoints}){const [state,setState]=useState({});useEffect(()=>{Promise.all(endpoints.map(e=>get(e).then(v=>({e,v})).catch(err=>({e,error:err.message})))).then(r=>setState(Object.fromEntries(r.map(x=>[x.e,x]))))},[title]);return <><PageHeader title={title} subtitle="Módulo React nativo conectado a las APIs existentes."/><div className="grid two">{endpoints.map(e=><div className="card" key={e}><div style={{display:'flex',gap:10,alignItems:'center'}}><Icon size={18}/><b>{e}</b></div><pre style={{whiteSpace:'pre-wrap',color:'#8fa0b8',fontSize:11,marginTop:15}}>{JSON.stringify(state[e]?.v??state[e]?.error??'Cargando…',null,2).slice(0,3000)}</pre></div>)}</div></>}
function PageHeader({title,subtitle}){return <div><h1 className="page-title">{title}</h1><p className="page-subtitle">{subtitle}</p></div>}

createRoot(document.getElementById('root')).render(<App/>);
